main/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from .views import *
urlpatterns = [
    path('register/',register_view.as_view(),name='register'),
    path('login/', UserLoginView.as_view(),name='Login' ),
    path('logout/', UserLogoutView.as_view(),{'next_page':''},name='Logout' ),
]

online_exam/urls.py
import os
from django.contrib import admin, auth
#from django.conf.urls import re_path
from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
# from ..teacher.views import QuestionList

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns = [
    path('', home,name='home'),
    path('admin/', admin.site.urls,name='admin'),
    re_path(r'^css/(?P<file>.*)$', css, name='css'),
    # path('student/', include('C:\Users\student\Desktop\Python\online_exam\teacher\urls.py')),
    path('teacher/', include((r'teacher.urls','teacher'),namespace='teacher')),
    path('student/', include((r'student.urls','student'),namespace='student')),
    re_path(r'^images/(.*)$',image , name='images'),
    path('contact/', contact,name='contact'),
    path('about/', about,name='about'),
    path('',include((r'main.urls','main'),namespace='main')),

]

student/urls.py
from django.contrib import admin, auth
from django.urls import path, include,re_path
from .views import *
urlpatterns = [
    path('', interface.as_view(),name='interface' ),
    #path('accnt/',include('django.contrib.auth.urls')),
    path('result/', Result.as_view(),name='result' ),
    path('choose_exam/', ChooseExam.as_view(),name='choose_exam' ),
    re_path(r'^exam/(?P<exam>.+)$',exam.as_view()),
]

student/models.py
from django.db import models

from .managers import *
# from ..teacher.models import


class Student(models.Model):
    object = StudentManager
    exams_given = models.ManyToManyField('student.exam_instance')

    def __str__(self):
        return str(self.id,)


class exam_instance(models.Model):
    exam_taker = models.ForeignKey('student.Student', on_delete=models.CASCADE)
    exam = models.ForeignKey('teacher.Exam', on_delete=models.SET_NULL,null=True)
    date = models.TimeField(auto_now_add=True)
    marks = models.IntegerField(null=True,)
    time_taken = models.IntegerField(default=0)
    # class Meta:
    #    unique_together = (('student', 'exam','date'),)
    def __str__(self):
        return str((self.id,))


class choices(models.Model):
    ex_inst = models.ForeignKey(exam_instance, on_delete=models.CASCADE)
    ans = models.CharField(
        max_length=1,
        choices=[
            ('a', 'a'),
            ('b', 'b'),
            ('c', 'c'),
            ('d', 'd')
        ],
        null=True)
    qs = models.ForeignKey('teacher.Question', on_delete=models.SET_NULL,null=True)
    # class Meta:
    #    unique_together = (('ex_inst', 'ans','qs'),)

teacher/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.core.validators import RegexValidator
from django.utils import timezone

# Create your models here.


class Database_Error(object):
    def __init__(self, arg):
        self._arg = arg

    def __call__(self, *args, **kwargs):
        val = self._arg(*args, **kwargs)
        print('called')
        return val


class Q_manage(models.Manager):
    @Database_Error
    def all(self):
        q = self.all()
        print('1')
        return ['hi']


class Question(models.Model):
    #Q_ID = models.IntegerField(unique=True, primary_key=True,auto_created=True)
    Question = models.CharField(max_length=100)
    Option1 = models.CharField(max_length=30)
    Option2 = models.CharField(max_length=30)
    Option3 = models.CharField(max_length=30)
    Option4 = models.CharField(max_length=30)
    Marks = models.IntegerField(default=0)
    Answer = models.CharField(
        max_length=1,
        choices=[
            ('a', Option1),
            ('b', Option2),
            ('c', Option3),
            ('d', Option4)
        ],
        null=True)

    objects = Q_manage

    @classmethod
    def modify_opt(cls, id, opt, new):
        Q = cls.objects.get(Q_ID=id)
        if opt == 'a':
            Q.Option1 = new
        elif opt == 'b':
            Q.Option2 = new
        elif opt == 'c':
            Q.Option3 = new
        elif opt == 'd':
            Q.Option4 = new
        else:
            raise Exception(
                "Invalid value for opt, allowed values =(a,b,c,d) ")
        Q.save()

    @classmethod
    def modify_qs(cls, id, new):
        Q = cls.objects.get(Q_ID=id)
        Q.Question = new
        Q.save()

    @classmethod
    def modify_ans(cls, id, new):
        Q = cls.objects.get(Q_ID=id)
        Q.Answer = new
        Q.save()

class QuestionPaper(models.Model):
    #Qp_ID = models.IntegerField(unique=True, primary_key=True)
    Questions = models.ManyToManyField(Question)
    created = models.DateTimeField(default=timezone.now,null=True)
    Full_Marks = models.IntegerField(default=0)
    Time_limit = models.IntegerField(default=0)


class Exam(models.Model):
    #Ex_ID = models.IntegerField(unique=True, primary_key=True)
    Subject=models.CharField(max_length=100,null=True,default='Computer Science')
    QP = models.ForeignKey(QuestionPaper, on_delete=models.SET_NULL,null=True)
    due_date = models.TimeField(null=True, blank=True)
    def __str__(self):
        return str((self.id,self.created))
    
class Teacher(models.Model):
    questions_created = models.ManyToManyField(Question)
    qp_created = models.ManyToManyField(QuestionPaper)
    exams_created = models.ManyToManyField(Exam)
    manages=models.ManyToManyField('teacher.Class')
    #user_prof=models.ForeignKey('student.Student')
    def __str__(self):
        return (self.id,)




class Class(models.Model):
    course= models.CharField(max_length=255, blank=True, null=True)
    incharge= models.ManyToManyField(Teacher)
    students= models.ManyToManyField('student.Student')

online_exam/views.py
from django.http import HttpResponse, FileResponse
from django.shortcuts import render
import os
#from ..main.forms import *
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, FormView, CreateView, ListView, UpdateView, DeleteView, DetailView, View

def home(request):
    return render(request, r"index.html")
    
    # if file:
    #     return render(request, r"Home/"+file)
    # else:
    #     return render(request, r"Home/index.html")
    


def css(request, file):
    print("css", file)
    return HttpResponse(request, file)  # +".css")\


def image(request, file):
    #print(request.GET)
    print("image", file)
    print(os.getcwd())
    img = open('templates/images/'+file, 'rb')
    #img = open('C:/Users/student/Desktop/Python/online_exam/online_exam/templates/images/'+file, 'rb')

    response = FileResponse(img)
    return response
# def invalid(request,url):
#    print
# C:/Users/student/Desktop/Python/online_exam/online_exam/templates/

def contact(req):
    return render(req,r"contact.html")
def about(req):
    return render(req,r"about.html")

student/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,AuthenticationForm
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.apps import apps

User=apps.get_model('main.User_new')
Exam=apps.get_model('teacher.Exam')
instance=apps.get_model('student.exam_instance')
def my_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        ...
    else:
        # Return an 'invalid login' error message.
        ...

# Create your views here.

# def interface(req):
#     return render(req, r"interface.html")

class interface(LoginRequiredMixin,TemplateView):
    def get(self,req):
        if req.user.is_authenticated:
            if req.user.is_student:
            #print(req.user.email,req.user.Institute_Name)
            #print(str(User.objects.get(pk=req.user.email).Institute_Name))
                return render(req, r"student/interface.html")
            else:
                return render(req,r"index_form.html",{'message':'You Do Not Have Required Permission'})
        else:
            return redirect(f"{settings.LOGIN_URL}?next={req.path}")
        #return render(req, r"index.html")

class Result(LoginRequiredMixin,TemplateView):
    def get(self,req):
        if req.user.is_authenticated:
            if req.user.is_student:
            #print(req.user.email,req.user.Institute_Name)
                user=(User.objects.get(pk=req.user.email))
                exam_list=(user.student_prof.exams_given.all())
                return render(req, r"student/result_temp.html",{'exam_list':exam_list})
            else:
                return render(req,r"index_form.html",{'message':'You Do Not Have Required Permission'})
        else:
            return redirect(f"{settings.LOGIN_URL}?next={req.path}")
class ChooseExam(LoginRequiredMixin,TemplateView):
    def get(self,req):
        if req.user.is_authenticated:
            if req.user.is_student:
            #print(req.user.email,req.user.Institute_Name)
                #user=(User.objects.get(pk=req.user.email))
                exam_list=(Exam.objects.all())
                return render(req, r"student/interface_temp.html",{'exam_list':exam_list})
            else:
                return render(req,r"index_form.html",{'message':'You Do Not Have Required Permission'})
        else:
            return redirect(f"{settings.LOGIN_URL}?next={req.path}")
class exam(LoginRequiredMixin,TemplateView):
    inst=None
    q_list=None
    def get(self,req,**kwargs):
        if req.user.is_authenticated:
            if req.user.is_student:
            #print(req.user.email,req.user.Institute_Name)
                self.user=(User.objects.get(pk=req.user.email))
                self.inst=instance(
                    exam_taker=self.user.student_prof,
                    exam=Exam.objects.get(pk=kwargs['exam'])
                    )
                
                self.q_list=Exam.objects.get(pk=kwargs['exam']).QP.Questions.all()
                print(Exam.objects.get(pk=kwargs['exam']).QP.Questions.all())
                return render(req, r"student/questions.html",{'q_list':enumerate(self.q_list,start=1)})
            else:
                return render(req,r"index_form.html",{'message':'You Do Not Have Required Permission'})
        else:
            return redirect(f"{settings.LOGIN_URL}?next={req.path}")
    def post(self,req,exam):
        print(req.POST)
        self.user=(User.objects.get(pk=req.user.email))
        self.inst=instance(
                exam_taker=self.user.student_prof,
                exam=Exam.objects.get(pk=exam)
                )
                
        self.q_list=self.inst.exam.QP.Questions.all()
        m=0
        for i in req.POST:
            if i[0]=='Q':
                if(self.q_list[int(i[1])-1].Answer==req.POST.get(i)):
                    m=m+self.q_list[int(i[1])-1].Marks
                #print(self.q_list[int(i[1])-1].Answer,req.POST.get(i))
        self.inst.marks=m
        self.inst.save()
        self.user.student_prof.exams_given.add(self.inst)
        self.user.student_prof.save()  
        return render(req,r"index_form.html",{'message':f'Exam Submitted Successfully, Marks Obtained: {m}/{self.inst.exam.QP.Full_Marks}'}) 

templates/student/adminLogin.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <title>Admin | Login</title>

</head>
<body>
    <header class="" id="header">
        <a href="./index.html" class="logo" id="#logo">OPEC - Online Examination Centre</a>
        <i class="bx bx-menu" id="menu-icon"></i>
        <nav class="navbar">
          <a href="./about.html">About</a>
          <a class="btn" id="btn-color" href="#">Contact Us</a>
        </nav>
      </header>
   <div class="box">
    <div class="container">

        <div class="top">
            <span>Have an account?</span>
            <div class="heading">Admin Login</div>
        </div>

        <div class="input-field">
            <input type="text" class="input" placeholder="Username" id="">
            <i class='bx bx-user' ></i>
        </div>

        <div class="input-field">
            <input type="Password" class="input" placeholder="Password" id="">
            <i class='bx bx-lock-alt'></i>
        </div>

        <div class="input-field">
            <input type="submit" class="submit" value="Login" id="">
        </div>

        <div class="two-col">
            <div class="one">
               <input type="checkbox" name="" id="check" required>
               <label for="check"> Remember Me</label>
            </div>
            <div class="two">
                <label><a href="#">Forgot password?</a></label>
            </div>
        </div>
    </div>
</div>
<section class="footer">
  <div class="main">
    <div class="list list-1">
      <h2>OPEC</h2>
      <div class="comp-desc">
        <p>
          OPEC is an online platform where examinations are conducted through online medium.
        </p>
      </div>
      <br>
      <div class="comp-desc">
        <p style="font-size: 16px">For queries:</p>
        <p>opec2023@gmail.com</p>
      </div>
      <div class="social">
        <a href="#"><i class='bx bxl-facebook sm-link'></i></a>
        <a href="#"><i class='bx bxl-instagram-alt sm-link'></i></a>
        <a href="#"><i class='bx bxl-twitter sm-link'></i></a>
        <a href="#"><i class='bx bxl-youtube sm-link'></i></a>
        <a href="#"><i class='bx bxl-linkedin sm-link'></i></a>
      </div>
    </div>


    <div class="list list-2">
      <h4>Useful Links</h4>
      <ul>
        <li><a href="contact-page.html">Contact US</a></li>
        <li><a href="community.html">Our Community</a></li>
      </ul>
    </div>

    <div class="list list-3">
      <h4>Designed By</h4>
      <ul>
        <li>Md Farhan Sajid - 2060010</li>
        <li>Anshuman Dhan - 2060007</li>
        <li>Ankit Kumar - 2060029</li>
        <li>Moni Kumari - 2060009</li>
        <li>Utkarsh Didwania - 2060004</li>
      </ul>
    </div>
  </div>

  <div class="footer-end">
    <div class="end-text">
      <p>Copyright &#169;2023 All rights reserved</p>
    </div>
  </div>
</section>
<script src="{% static 'JS/index.js' %}"></script>
</body>
</html>

templates/student/interface.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OPEC - Online Platform for Examination Centre</title>
    
    <!-- Boxicon -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Custom CSS file -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/interface.css' %}" >

  </head>
  <body>
  {%include 'student/studentheader.html'%}
    <section class="interface">
      {%include 'student/studentNavBar.html'%}
      <div class="rightdiv">
        <div class="topdiv">
          <h1>Student Interface</h1>
          <h3>View Profile</h3>
        </div>
        <div class="container">
          <div class="imgdiv">
            <img src="{% static 'images/profilePic.jpg' %}" alt="Profile picture">
            <div class="details">
              <h1>{{request.user.Name}}</h1>
              <h5>(Student ID:{{request.user.User_ID}})</h5>
            </div>
          </div>
          <div class="info">
            <div class="set">
              <p class="heading">Email Address:</p>
              <p class="value">{{request.user.email}}</p>
            </div>
            <div class="set">
              <p class="heading">Institute Name:</p>
              <p class="value">{{request.user.Institute_Name}}</p>
            </div>
            <div class="set">
              <p class="heading">Institute ID:</p>
              <p class="value">{{request.user.Institute_ID}}</p>
            </div>
            <div class="set">
              <p class="heading">Phone Number:</p>
              <p class="value">{{request.user.phone}}</p>
            </div>
           <div class="set">
              <p class="heading">Date Joined:</p>
              <p class="value">{{request.user.date_joined}}</p>
            </div>
            <!-- 
            <div class="set">
              <p class="heading">Blood Group:</p>
              <p class="value">A+</p>
            </div>
            <div class="set">
              <p class="heading">Address:</p>
              <p class="value">4, Amrita Shergill Road <br>New Delhi <br>110003 <br>India</p>
            </div>-->
          </div>
          <div class="button">
            <a href="#" class="btn2">Update Info</a>
          </div>
          
        </div>
      </div>
    </section>

    {%include 'footer.html'%}

    <script src="{% static 'JS/index.js' %}"></script>
  </body>
</html>

templates/student/interface_form.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OPEC - Online Platform for Examination Centre</title>
    
    <!-- Boxicon -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Custom CSS file -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/interface.css' %}" >

  </head>
  <body>
  {%include 'student/studentheader.html'%}
    <section class="interface">
      {%include 'student/studentNavBar.html'%}
      <div class="rightdiv">
        <div class="topdiv">
          <h1>Student Interface</h1>
          
        </div>
        <div class="container">
          <form method="POST">{% csrf_token %}
            {{form.as_p}}
            <!--{{ form.non_field_errors }}
            <p>
            <label for="id_question" class="login-labels">Question*</label> 
            {{ form.Question.errors }}
            {{ form.Question}}
            </p><p>
            <label for="id_Option1" class="login-labels">Option1*:</label> 
            {{ form.Option1.errors }}
            {{ form.Option1}}
          </p><p>
            <label for="id_Option2" class="login-labels">Option2*:</label> 
            {{ form.Option2.errors }}
            {{ form.Option2}}
          </p><p>
            <label for="id_Option3" class="login-labels">Option3*:</label> 
            {{ form.Option3.errors }}
            {{ form.Option3}}
          </p><p>
            <label for="id_Option4" class="login-labels">Option4*:</label> 
            {{ form.Option4.errors }}
            {{ form.Option4}}
          </p><p>


            <label for="id_Answer" class="login-labels">Answer*</label> 
            {{ form.Answer.errors }}
            {{ form.Answer}}
          </p><p>
            <label for="id_Marks" class="login-labels">Marks</label> 
            {{ form.Marks.errors }}
            {{ form.Marks}}
          </p>-->
          <p>
            <button type="submit" class="btn btn-primary">Submit</button>
            </p>
          </form>
        </div>
      </div>
    </section>

    {%include 'footer.html'%}

    <script src="{% static 'JS/index.js' %}"></script>
  </body>
</html>

templates/student/interface_temp.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OPEC - Online Platform for Examination Centre</title>
    
    <!-- Boxicon -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Custom CSS file -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/interface.css' %}" >
    <style>
      
      .result {
        margin-bottom: 20px;
        padding: 10px;
        background-color: #f0f0f0;
        border-radius: 5px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
      }
      .subject {
        font-weight: bold;
        margin-bottom: 5px;
      }
      .details {
        font-size: 14px;
        color: #666;
        margin-bottom: 10px;
      }
      .date {
        margin-right: 10px;
      }
    </style>
  </head>
  <body>
  {%include 'student/studentheader.html'%}
    <section class="interface">
      {%include 'student/studentNavBar.html'%}
      <div class="rightdiv">
        <div class="topdiv">
          <h1>Student Interface</h1>
          
        </div>
        <div class="container">
          
            {% for i in exam_list %}
            <a href="{% url 'student:interface' %}exam/{{i.id}}"><div class="result">
              <div class="subject">{{i.Subject}}</div>
              <div class="details">
                <span class="date">Due date:</span> {{i.Due_Date}} 
              </div>
              <div class="details">
                <span class="name">Exam ID:</span>{{i.id}}
              </div>
              <div class="details">
                <span class="score">Full Marks:</span>{{i.QP.Full_Marks}} 
              </div></a>
            </div>
            {% endfor %}
            <!--{{ form.non_field_errors }}
            <p>
            <label for="id_question" class="login-labels">Question*</label> 
            {{ form.Question.errors }}
            {{ form.Question}}
            </p><p>
            <label for="id_Option1" class="login-labels">Option1*:</label> 
            {{ form.Option1.errors }}
            {{ form.Option1}}
          </p><p>
            <label for="id_Option2" class="login-labels">Option2*:</label> 
            {{ form.Option2.errors }}
            {{ form.Option2}}
          </p><p>
            <label for="id_Option3" class="login-labels">Option3*:</label> 
            {{ form.Option3.errors }}
            {{ form.Option3}}
          </p><p>
            <label for="id_Option4" class="login-labels">Option4*:</label> 
            {{ form.Option4.errors }}
            {{ form.Option4}}
          </p><p>


            <label for="id_Answer" class="login-labels">Answer*</label> 
            {{ form.Answer.errors }}
            {{ form.Answer}}
          </p><p>
            <label for="id_Marks" class="login-labels">Marks</label> 
            {{ form.Marks.errors }}
            {{ form.Marks}}
          </p>-->
          
        </div>
      </div>
    </section>

    {%include 'footer.html'%}

    <script src="{% static 'JS/index.js' %}"></script>
  </body>
</html>

templates/student/questions.html
<!DOCTYPE html>
<html>
  {% load static %}
  <head>
     <!-- Boxicon -->
     <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

     <!-- Custom CSS file -->
     <link rel="stylesheet" href="{% static 'css/index.css' %}" >
     <link rel="stylesheet" href="{% static 'css/interface.css' %}" >
 
    <title> Examination Questions</title>
    <link rel="stylesheet" href="{% static 'css/questions.css' %}">
  </head>
  <body>
    {%include 'student/studentheader.html'%}
    <!--{%include 'student/studentNavBar.html'%}-->
    <section class="top">
      <h1>Multiple Choice Examination Questions</h1>
      <hr>
    </section>
    
    <div class="container" style="padding:20px ; max-width: 780px;">
      <form method="POST">{% csrf_token %}
        {% for j,i in q_list %}
      <div class="question">
        <h2>Question {{j}}:</h2>
        <p>{{i.Question}}</p>
        <input type="radio" name="Q{{j}}" value="a" id="Q{{j}}a">
        <label for="Q{{j}}a">a) {{i.Option1}}</label><br>
        <input type="radio" name="Q{{j}}" value="b" id="Q{{j}}b">
        <label for="Q{{j}}b">b) {{i.Option2}}</label><br>
        <input type="radio" name="Q{{j}}" value="c" id="Q{{j}}c">
        <label for="Q{{j}}c">c) {{i.Option3}}</label><br>
        <input type="radio" name="Q{{j}}" value="d" id="Q{{j}}d">
        <label for="Q{{j}}d">d) {{i.Option4}}</label><br>
      </div>
      {% endfor %}
      <button type="submit">Submit</button>
    </div>
    {%include 'footer.html'%}
  </body>
</html>

templates/student/result_temp.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OPEC - Online Platform for Examination Centre</title>
    
    <!-- Boxicon -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Custom CSS file -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/interface.css' %}" >
    <style>
      
      .result {
        margin-bottom: 20px;
        padding: 10px;
        background-color: #f0f0f0;
        border-radius: 5px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
      }
      .subject {
        font-weight: bold;
        margin-bottom: 5px;
      }
      .details {
        font-size: 14px;
        color: #666;
        margin-bottom: 10px;
      }
      .date {
        margin-right: 10px;
      }
    </style>
  </head>
  <body>
  {%include 'student/studentheader.html'%}
    <section class="interface">
      {%include 'student/studentNavBar.html'%}
      <div class="rightdiv">
        <div class="topdiv">
          <h1>Student Interface</h1>
          
        </div>
        <div class="container">
          
            {% for i in exam_list %}
            <div class="subject">{{i.exam.Subject}}</div>
              <div class="details">
                <span class="date">Date:</span> {{i.date}} 
              </div>
              <div class="details">
                <span class="name">Instance ID:</span>{{i.id}}
              </div>
              <div class="details">
                <span class="name">Exam ID:</span>{{i.exam.id}}
              </div>
              <div class="details">
                <span class="score">Marks:</span>{{i.marks}} 
              </div>
            {% endfor %}
            <!--{{ form.non_field_errors }}
            <p>
            <label for="id_question" class="login-labels">Question*</label> 
            {{ form.Question.errors }}
            {{ form.Question}}
            </p><p>
            <label for="id_Option1" class="login-labels">Option1*:</label> 
            {{ form.Option1.errors }}
            {{ form.Option1}}
          </p><p>
            <label for="id_Option2" class="login-labels">Option2*:</label> 
            {{ form.Option2.errors }}
            {{ form.Option2}}
          </p><p>
            <label for="id_Option3" class="login-labels">Option3*:</label> 
            {{ form.Option3.errors }}
            {{ form.Option3}}
          </p><p>
            <label for="id_Option4" class="login-labels">Option4*:</label> 
            {{ form.Option4.errors }}
            {{ form.Option4}}
          </p><p>


            <label for="id_Answer" class="login-labels">Answer*</label> 
            {{ form.Answer.errors }}
            {{ form.Answer}}
          </p><p>
            <label for="id_Marks" class="login-labels">Marks</label> 
            {{ form.Marks.errors }}
            {{ form.Marks}}
          </p>-->
          
        </div>
      </div>
    </section>

    {%include 'footer.html'%}

    <script src="{% static 'JS/index.js' %}"></script>
  </body>
</html>

templates/student/studentNavBar.html
<div class="leftdiv">
    <div class="options">
      <ul>
        <li><a href="{% url 'student:interface' %}">Personal Information</a></li>
        <li><a href="{% url 'student:result' %}">Check Results</a></li>
        <li><a href="{% url 'student:choose_exam' %}">Choose Exam</a></li>
        <li class="last"><a href="{% url 'main:Logout' %}" class="btn2 btn3">Logout</a></li>
      </ul>
    </div>
  </div>

templates/student/studentheader.html
<header class="" id="header">
  <a href="{% url 'home' %}" class="logo" id="#logo">OPEC - Online Examination Centre</a>
  <i class="bx bx-menu" id="menu-icon"></i>
  <nav class="navbar">
    <a href="{% url 'student:interface' %}" class="temp">Personal Information</a>
    <a href="{% url 'student:result' %}" class="temp">Check Results</a>
    <a href="{% url 'student:choose_exam' %}" class="temp last">Choose exam</a>
    <a href="{% url 'about' %}">About</a>
    <a class="btn" id="btn-color" href="{% url 'contact' %}">Contact Us</a>
  </nav>
</header>
