main/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from .views import *
urlpatterns = [
    path('register/',register_view.as_view(),name='register'),
    path('login/', UserLoginView.as_view(),name='Login' ),
    path('logout/', UserLogoutView.as_view(),{'next_page':''},name='Logout' ),
]

online_exam/urls.py
import os
from django.contrib import admin, auth
#from django.conf.urls import re_path
from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
# from ..teacher.views import QuestionList

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns = [
    path('', home,name='home'),
    path('admin/', admin.site.urls,name='admin'),
    re_path(r'^css/(?P<file>.*)$', css, name='css'),
    # path('student/', include('C:\Users\student\Desktop\Python\online_exam\teacher\urls.py')),
    path('teacher/', include((r'teacher.urls','teacher'),namespace='teacher')),
    path('student/', include((r'student.urls','student'),namespace='student')),
    re_path(r'^images/(.*)$',image , name='images'),
    path('contact/', contact,name='contact'),
    path('about/', about,name='about'),
    path('',include((r'main.urls','main'),namespace='main')),

]

teacher/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from .views import *
urlpatterns = [
    path('', interface.as_view(),name='interface' ),
    path('qs/', QuestionList),
    path('Create_Question/', CreateQuestion.as_view(),name="create_question"),
    path('Create_QuestionPaper/', CreateQuestionPaper.as_view(),name="create_question_paper"),
    path('Set_Exam/', SetExam.as_view(),name="set_exam"),
    path('result/', Result.as_view(),name='result' ),
]

teacher/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.core.validators import RegexValidator
from django.utils import timezone

# Create your models here.


class Database_Error(object):
    def __init__(self, arg):
        self._arg = arg

    def __call__(self, *args, **kwargs):
        val = self._arg(*args, **kwargs)
        print('called')
        return val


class Q_manage(models.Manager):
    @Database_Error
    def all(self):
        q = self.all()
        print('1')
        return ['hi']


class Question(models.Model):
    #Q_ID = models.IntegerField(unique=True, primary_key=True,auto_created=True)
    Question = models.CharField(max_length=100)
    Option1 = models.CharField(max_length=30)
    Option2 = models.CharField(max_length=30)
    Option3 = models.CharField(max_length=30)
    Option4 = models.CharField(max_length=30)
    Marks = models.IntegerField(default=0)
    Answer = models.CharField(
        max_length=1,
        choices=[
            ('a', Option1),
            ('b', Option2),
            ('c', Option3),
            ('d', Option4)
        ],
        null=True)

    objects = Q_manage

    @classmethod
    def modify_opt(cls, id, opt, new):
        Q = cls.objects.get(Q_ID=id)
        if opt == 'a':
            Q.Option1 = new
        elif opt == 'b':
            Q.Option2 = new
        elif opt == 'c':
            Q.Option3 = new
        elif opt == 'd':
            Q.Option4 = new
        else:
            raise Exception(
                "Invalid value for opt, allowed values =(a,b,c,d) ")
        Q.save()

    @classmethod
    def modify_qs(cls, id, new):
        Q = cls.objects.get(Q_ID=id)
        Q.Question = new
        Q.save()

    @classmethod
    def modify_ans(cls, id, new):
        Q = cls.objects.get(Q_ID=id)
        Q.Answer = new
        Q.save()

class QuestionPaper(models.Model):
    #Qp_ID = models.IntegerField(unique=True, primary_key=True)
    Questions = models.ManyToManyField(Question)
    created = models.DateTimeField(default=timezone.now,null=True)
    Full_Marks = models.IntegerField(default=0)
    Time_limit = models.IntegerField(default=0)


class Exam(models.Model):
    #Ex_ID = models.IntegerField(unique=True, primary_key=True)
    Subject=models.CharField(max_length=100,null=True,default='Computer Science')
    QP = models.ForeignKey(QuestionPaper, on_delete=models.SET_NULL,null=True)
    due_date = models.TimeField(null=True, blank=True)
    def __str__(self):
        return str((self.id,self.created))
    
class Teacher(models.Model):
    questions_created = models.ManyToManyField(Question)
    qp_created = models.ManyToManyField(QuestionPaper)
    exams_created = models.ManyToManyField(Exam)
    manages=models.ManyToManyField('teacher.Class')
    #user_prof=models.ForeignKey('student.Student')
    def __str__(self):
        return (self.id,)




class Class(models.Model):
    course= models.CharField(max_length=255, blank=True, null=True)
    incharge= models.ManyToManyField(Teacher)
    students= models.ManyToManyField('student.Student')

teacher/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import *
from django import forms
from django.core.validators import RegexValidator

class CreateQuestionsForm(forms.ModelForm):
    # email = forms.EmailField(required=True)
    # name = forms.CharField(max_length=5, required=True)
    
    # phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
    # phone = forms.CharField(max_length=255, required=True, validators=[phone_regex])
    # query = forms.CharField(widget = forms.Textarea)
    class Meta:
        model = Question
        fields = [
            'Question',
            'Option1',
            'Option2',
            'Option3',
            'Option4',
            'Marks',
            'Answer'
        ]
class SetExamForm(forms.ModelForm):
    # email = forms.EmailField(required=True)
    # name = forms.CharField(max_length=5, required=True)
    
    # phone_regex = RegexValidator( regex = r'^\d{10}$',message = "phone number should exactly be in 10 digits")
    # phone = forms.CharField(max_length=255, required=True, validators=[phone_regex])
    # query = forms.CharField(widget = forms.Textarea)
    class Meta:
        model = Exam
        fields = [
            'QP',
            'Subject',
            
        ]

teacher/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import *

from django.views.generic import TemplateView, FormView, CreateView, ListView, UpdateView, DeleteView, DetailView, View
from django.db.models import Q
from .forms import *
from django.urls import reverse_lazy, reverse
#from .models import SellerAdditional, CustomUser, Contact, Product, ProductInCart, Cart
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.apps import apps

User=apps.get_model('main.User_new')
Exam=apps.get_model('teacher.Exam')
Instance=apps.get_model('student.exam_instance')
# Create your views here.
def QuestionList(Request):
    t=Question.objects.all()
    print(t)
    return HttpResponse(t)

class CreateQuestion(LoginRequiredMixin,FormView):
    form_class = CreateQuestionsForm
    template_name = 'teacher/interface_form.html'
    #success_url = '/'   #hardcoded url
    success_url = reverse_lazy('teacher:create_question')
    def form_valid(self, form):
        user=User.objects.get(pk=self.request.user.email)
        #print(self.request.user.email)
        # if len(form.cleaned_data.get('query'))>10:
        #     form.add_error('query', 'Query length is not right')
        # return render(self.request, 'interface_form.html', {'form':form})
        #print(form.save())
        user.teacher_prof.questions_created.add(form.save())
        user.teacher_prof.save()
        #print(user.teacher_prof.questions_created.all())
        response = super().form_valid(form)
        return response

    '''def form_invalid(self, form):
        if len(form.cleaned_data.get('query'))>10:
            form.add_error('query', 'Query length is not right')
            #form.errors['__all__'] = 'Query length is not right. It should be in 10 digits.'
        response = super().form_invalid(form)
        return response'''
class interface(LoginRequiredMixin,TemplateView):
    def get(self,req):
        if req.user.is_authenticated:
            if req.user.is_teacher:
                
            #print(req.user.email,req.user.Institute_Name)
            #print(str(User.objects.get(pk=req.user.email).Institute_Name))
                return render(req, r"teacher/interface.html")
            else:
                return render(req,r"index_form.html",{'message':'You Do Not Have Required Permission'})
        else:
            return redirect(f"{settings.LOGIN_URL}?next={req.path}")
        #return render(req, r"index.html")
class CreateQuestionPaper(LoginRequiredMixin,TemplateView):
    template_name = 'teacher/interface_temp.html'
    #success_url = '/'   #hardcoded url
    success_url = reverse_lazy('teacher:create_question')
    def get(self,req):
        if req.user.is_authenticated:
            if req.user.is_teacher:
                user=User.objects.get(pk=req.user.email)
                q_list=user.teacher_prof.questions_created.all()
                print("get",q_list)
            #print(req.user.email,req.user.Institute_Name)
            #print(str(User.objects.get(pk=req.user.email).Institute_Name))
                return render(req, r"teacher/set_qp.html",{'q_list':enumerate(q_list,start=1)})
            else:
                return render(req,r"index_form.html",{'message':'You Do Not Have Required Permission'})
        else:
            return redirect(f"{settings.LOGIN_URL}?next={req.path}")
    def post(self, req):
        user=User.objects.get(pk=req.user.email)
        print("post req",req.POST)
        q_list=[]
        for i in req.POST:
            if i[0]=='Q':
             print("Q",req.POST[i])
             q_list.append(
                 Question.objects.get(pk=req.POST[i])
             )   
        m=0
        qp=QuestionPaper()
        qp.save()
        for i in q_list:
            m=m+i.Marks
            qp.Questions.add(i)
            qp.save()
        qp.Full_Marks=m
        print("qp",qp.Questions.all())
        qp.save()
        #print(qp,qp.Full_Marks,qp.Questions.all())
        #user.teacher_prof.questions_created.add(form.save())
        #response = super().form_valid(form)
        return redirect(reverse_lazy('teacher:create_question_paper'))

class SetExam(LoginRequiredMixin,FormView):
    form_class = SetExamForm
    template_name = 'teacher/interface_form.html'
    #success_url = '/'   #hardcoded url
    success_url = reverse_lazy('teacher:set_exam')
    def form_valid(self, form):
        user=User.objects.get(pk=self.request.user.email)
        print(form.cleaned_data['QP'].Questions.all())
        # if len(form.cleaned_data.get('query'))>10:
        #     form.add_error('query', 'Query length is not right')
        # return render(self.request, 'interface_form.html', {'form':form})
        #print(form.save())
        user.teacher_prof.exams_created.add(form.save())
        user.teacher_prof.save()
        #print(user.teacher_prof.questions_created.all())
        response = super().form_valid(form)
        return response
    

class Result(LoginRequiredMixin,TemplateView):
    def get(self,req):
        if req.user.is_authenticated:
            if req.user.is_teacher:
            #print(req.user.email,req.user.Institute_Name)
                inst_list=[]
                #print(req.POST)
                if len(req.GET)>1:
                    print(req.GET)
                    if len(req.GET['id'])>0 and len(req.GET['name'])==0:
                        print(1)
                        users=(User.objects.filter(User_ID=req.GET['id'][0]))
                    elif len(req.GET['id'])==0 and len(req.GET['name'])>0:
                        print(2)
                        users=User.objects.filter(
                            Name__icontains=req.GET['name'][0]
                            )
                    elif len(req.GET['id'])>0 and len(req.GET['name'])>0:
                        print(3)
                        users=(User.objects.filter(
                            Name__icontains=req.GET['name'][0],
                            User_ID=req.GET['id'][0])
                            )
                    else:
                        print(4)
                        users=(User.objects.all())
                    student=[]
                    
                    exam_list=(req.user.teacher_prof.exams_created.all())
                    inst_list=[]
                    for i in users:
                        student=(i.student_prof)
                        if i.is_student:
                            j=Instance.objects.filter(exam_taker=student,exam__in=exam_list)
                            if len(j)>0:
                                inst_list.append((i.Name,j))
                    #print(inst_list.order_by('exam_taker'))
                return render(req, r"teacher/result_temp.html",{'inst_list':inst_list})
            else:
                return render(req,r"index_form.html",{'message':'You Do Not Have Required Permission'})
        else:
            return redirect(f"{settings.LOGIN_URL}?next={req.path}")

templates/teacher/interface_form.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OPEC - Online Platform for Examination Centre</title>
    
    <!-- Boxicon -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Custom CSS file -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/interface.css' %}" >

  </head>
  <body>
  {%include 'teacher/teacherheader.html'%}
  <section class="interface">
    {%include 'teacher/teacherNavBar.html'%}
    <div class="rightdiv">
      <div class="topdiv">
        <h1>Teacher Interface</h1>
        
        </div>
        <div class="container">
          <form method="POST">{% csrf_token %}
            {{form.as_p}}
            <!--{{ form.non_field_errors }}
            <p>
            <label for="id_question" class="login-labels">Question*</label> 
            {{ form.Question.errors }}
            {{ form.Question}}
            </p><p>
            <label for="id_Option1" class="login-labels">Option1*:</label> 
            {{ form.Option1.errors }}
            {{ form.Option1}}
          </p><p>
            <label for="id_Option2" class="login-labels">Option2*:</label> 
            {{ form.Option2.errors }}
            {{ form.Option2}}
          </p><p>
            <label for="id_Option3" class="login-labels">Option3*:</label> 
            {{ form.Option3.errors }}
            {{ form.Option3}}
          </p><p>
            <label for="id_Option4" class="login-labels">Option4*:</label> 
            {{ form.Option4.errors }}
            {{ form.Option4}}
          </p><p>


            <label for="id_Answer" class="login-labels">Answer*</label> 
            {{ form.Answer.errors }}
            {{ form.Answer}}
          </p><p>
            <label for="id_Marks" class="login-labels">Marks</label> 
            {{ form.Marks.errors }}
            {{ form.Marks}}
          </p>-->
          <p>
            <button type="submit" class="btn btn-primary">Submit</button>
            </p>
          </form>
        </div>
      </div>
    </section>

    {%include 'footer.html'%}

    <script src="{% static 'JS/index.js' %}"></script>
  </body>
</html>

templates/teacher/interface_temp.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OPEC - Online Platform for Examination Centre</title>
    
    <!-- Boxicon -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Custom CSS file -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/interface.css' %}" >
    <style>
      
      .result {
        margin-bottom: 20px;
        padding: 10px;
        background-color: #f0f0f0;
        border-radius: 5px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
      }
      .subject {
        font-weight: bold;
        margin-bottom: 5px;
      }
      .details {
        font-size: 14px;
        color: #666;
        margin-bottom: 10px;
      }
      .date {
        margin-right: 10px;
      }
    </style>
  </head>
  <body>
    {%include 'teacher/teacherheader.html'%}
    <section class="interface">
      {%include 'teacher/teacherNavBar.html'%}
      <div class="rightdiv">
        <div class="topdiv">
          <h1>Teacher Interface</h1>
         
        </div>
        <div class="container">
          <form method="POST">{% csrf_token %}
            {% for j,i in q_list %}
            <div class="result">
              <input type="checkbox" id="Q{{j}}" name="Q{{j}}" value="{{i.id}}">
              <div class="details">
                <span class="subject">Question:</span> {{i.Question}}
              </div>
              <div class="name">Q _ID:    {{i.id}}</div>
              
              <div class="details">
                <span class="name">(a):</span> {{i.Option1}}
              </div>
              <div class="details">
                <span class="name">(b):</span> {{i.Option2}}
              </div>
              <div class="details">
                <span class="name">(c):</span> {{i.Option3}}
              </div>
              <div class="details">
                <span class="name">(d):</span> {{i.Option4}}
              </div>
              <div class="details">
                <span class="score">Marks:</span>{{i.Marks}}
              </div>
            </div>
            {% endfor %}
            <!--{{ form.non_field_errors }}
            <p>
            <label for="id_question" class="login-labels">Question*</label> 
            {{ form.Question.errors }}
            {{ form.Question}}
            </p><p>
            <label for="id_Option1" class="login-labels">Option1*:</label> 
            {{ form.Option1.errors }}
            {{ form.Option1}}
          </p><p>
            <label for="id_Option2" class="login-labels">Option2*:</label> 
            {{ form.Option2.errors }}
            {{ form.Option2}}
          </p><p>
            <label for="id_Option3" class="login-labels">Option3*:</label> 
            {{ form.Option3.errors }}
            {{ form.Option3}}
          </p><p>
            <label for="id_Option4" class="login-labels">Option4*:</label> 
            {{ form.Option4.errors }}
            {{ form.Option4}}
          </p><p>


            <label for="id_Answer" class="login-labels">Answer*</label> 
            {{ form.Answer.errors }}
            {{ form.Answer}}
          </p><p>
            <label for="id_Marks" class="login-labels">Marks</label> 
            {{ form.Marks.errors }}
            {{ form.Marks}}
          </p>-->
          <p>
            <button type="submit" class="btn btn-primary">Submit</button>
            </p>
          </form>
        </div>
      </div>
    </section>

    {%include 'footer.html'%}

    <script src="{% static 'JS/index.js' %}"></script>
  </body>
</html>

templates/teacher/result.html
<!DOCTYPE html>
<html>
<head>
	<title>Result Display Page</title>
	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f5f5f5;
		}
		h1 {
			text-align: center;
			margin-top: 50px;
		}

    h2 {
			text-align: center;
			margin-top: 50px;
		}

		.container {
			max-width: 800px;
			margin: 0 auto;
			padding: 20px;
			background-color: #fff;
			border-radius: 10px;
			box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
		}
		.result {
			margin-bottom: 20px;
			padding: 10px;
			background-color: #f0f0f0;
			border-radius: 5px;
			box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
		}
		.subject {
			font-weight: bold;
			margin-bottom: 5px;
		}
		.details {
			font-size: 14px;
			color: #666;
			margin-bottom: 10px;
		}
		.date {
			margin-right: 10px;
		}
	</style>
</head>
<body>
	<h1>Results</h1>
  <h2>Name: Utkarsh Didwania</h2>

	<div class="container">
		<div class="result">
			<div class="subject">Mathematics</div>
			<div class="details">
				<span class="date">Exam date:</span> January 15, 2023
			</div>
			<div class="details">
				<span class="name">Column:</span> ABC
			</div>
			<div class="details">
				<span class="score">Score:</span> 85%
			</div>
		</div>
		<div class="result">
			<div class="subject">Science</div>
			<div class="details">
				<span class="date">Exam date:</span> February 1, 2023
			</div>
			<div class="details">
				<span class="name">Column:</span> DEF
			</div>
			<div class="details">
				<span class="score">Score:</span> 92%
			</div>
		</div>
		<div class="result">
			<div class="subject">English</div>
			<div class="details">
				<span class="date">Exam date:</span> March 12, 2023
			</div>
			<div class="details">
				<span class="name">Column:</span> IJK
			</div>
			<div class="details">
				<span class="score">Score:</span> 78%
			</div>
		</div>
	</div>
</body>
</html>

templates/teacher/result_temp.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OPEC - Online Platform for Examination Centre</title>
    
    <!-- Boxicon -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Custom CSS file -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/interface.css' %}" >
    <style>
      
      .result {
        margin-bottom: 20px;
        padding: 10px;
        background-color: #f0f0f0;
        border-radius: 5px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
      }
      .subject {
        font-weight: bold;
        margin-bottom: 5px;
      }
      .details {
        font-size: 14px;
        color: #666;
        margin-bottom: 10px;
      }
      .date {
        margin-right: 10px;
      }
    </style>
  </head>
  <body>
  {%include 'teacher/teacherheader.html'%}
    <section class="interface">
      {%include 'teacher/teacherNavBar.html'%}
      <div class="rightdiv">
        <div class="topdiv">
          <h1>Teacher Interface</h1>
          
        </div>
        <div class="container">
          <form method="GET">
            <div class="input-field">
              <input type="text" class="input" name="id" placeholder="Student ID" id="id">
              <i class='bx bx-user' ></i>
          </div>
          <div class="input-field">
            <input type="text" class="input" name="name" placeholder="Student Name" id="name">
            <i class='bx bx-user' ></i>
        </div>
            <p>
              <button type="submit" class="btn btn-primary">Submit</button>
              </p>
            </form>
            {% for i,j in inst_list %}
            <div class="subject">{{i}}</div>
            <div class="subject">{{j.exam.Subject}}</div>
              <div class="details">
                <span class="date">Date:</span> {{j.date}} 
              </div>
              <div class="details">
                <span class="name">Instance ID:</span>{{j.id}}
              </div>
              <div class="details">
                <span class="name">Exam ID:</span>{{j.exam.id}}
              </div>
              <div class="details">
                <span class="score">Marks:</span>{{j.marks}} 
              </div>
            {% endfor %}
            <!--{{ form.non_field_errors }}
            <p>
            <label for="id_question" class="login-labels">Question*</label> 
            {{ form.Question.errors }}
            {{ form.Question}}
            </p><p>
            <label for="id_Option1" class="login-labels">Option1*:</label> 
            {{ form.Option1.errors }}
            {{ form.Option1}}
          </p><p>
            <label for="id_Option2" class="login-labels">Option2*:</label> 
            {{ form.Option2.errors }}
            {{ form.Option2}}
          </p><p>
            <label for="id_Option3" class="login-labels">Option3*:</label> 
            {{ form.Option3.errors }}
            {{ form.Option3}}
          </p><p>
            <label for="id_Option4" class="login-labels">Option4*:</label> 
            {{ form.Option4.errors }}
            {{ form.Option4}}
          </p><p>


            <label for="id_Answer" class="login-labels">Answer*</label> 
            {{ form.Answer.errors }}
            {{ form.Answer}}
          </p><p>
            <label for="id_Marks" class="login-labels">Marks</label> 
            {{ form.Marks.errors }}
            {{ form.Marks}}
          </p>-->
          
        </div>
      </div>
    </section>

    {%include 'footer.html'%}

    <script src="{% static 'JS/index.js' %}"></script>
  </body>
</html>

templates/teacher/set_qp.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OPEC - Online Platform for Examination Centre</title>
    
    <!-- Boxicon -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Custom CSS file -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/interface.css' %}" >
    <style>
      
      .result {
        margin-bottom: 20px;
        padding: 10px;
        background-color: #f0f0f0;
        border-radius: 5px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
      }
      .subject {
        font-weight: bold;
        margin-bottom: 5px;
      }
      .details {
        font-size: 14px;
        color: #666;
        margin-bottom: 10px;
      }
      .date {
        margin-right: 10px;
      }
    </style>
  </head>
  <body>
    {%include 'teacher/teacherheader.html'%}
    <section class="interface">
      {%include 'teacher/teacherNavBar.html'%}
      <div class="rightdiv">
        <div class="topdiv">
          <h1>Teacher Interface</h1>
         
        </div>
        <div class="container">
          <form method="POST">{% csrf_token %}
            {% for j,i in q_list %}
            <div class="result">
              <input type="checkbox" id="Q{{j}}" name="Q{{j}}" value="{{i.id}}">
              <div class="details">
                <span class="subject">Question:</span> {{i.Question}}
              </div>
              <div class="name">Q _ID:    {{i.id}}</div>
              
              <div class="details">
                <span class="name">(a):</span> {{i.Option1}}
              </div>
              <div class="details">
                <span class="name">(b):</span> {{i.Option2}}
              </div>
              <div class="details">
                <span class="name">(c):</span> {{i.Option3}}
              </div>
              <div class="details">
                <span class="name">(d):</span> {{i.Option4}}
              </div>
              <div class="details">
                <span class="score">Marks:</span>{{i.Marks}}
              </div>
              <div class="name">Answer:    {{i.Answer}}</div>
            </div>
            {% endfor %}
            <!--{{ form.non_field_errors }}
            <p>
            <label for="id_question" class="login-labels">Question*</label> 
            {{ form.Question.errors }}
            {{ form.Question}}
            </p><p>
            <label for="id_Option1" class="login-labels">Option1*:</label> 
            {{ form.Option1.errors }}
            {{ form.Option1}}
          </p><p>
            <label for="id_Option2" class="login-labels">Option2*:</label> 
            {{ form.Option2.errors }}
            {{ form.Option2}}
          </p><p>
            <label for="id_Option3" class="login-labels">Option3*:</label> 
            {{ form.Option3.errors }}
            {{ form.Option3}}
          </p><p>
            <label for="id_Option4" class="login-labels">Option4*:</label> 
            {{ form.Option4.errors }}
            {{ form.Option4}}
          </p><p>


            <label for="id_Answer" class="login-labels">Answer*</label> 
            {{ form.Answer.errors }}
            {{ form.Answer}}
          </p><p>
            <label for="id_Marks" class="login-labels">Marks</label> 
            {{ form.Marks.errors }}
            {{ form.Marks}}
          </p>-->
          <p>
            <button type="submit" class="btn btn-primary">Submit</button>
            </p>
          </form>
        </div>
      </div>
    </section>

    {%include 'footer.html'%}

    <script src="{% static 'JS/index.js' %}"></script>
  </body>
</html>

templates/teacher/teacherNavBar.html
<div class="leftdiv">
    <div class="options">
      <ul>
        <li><a href="{% url 'teacher:interface' %}">Personal Information</a></li>
<!--<li><a href="{% url 'teacher:result' %}">Check Results</a></li>-->
        
        <li><a href="{% url 'teacher:create_question' %}">Set Questions</a></li>
        <li><a href="{% url 'teacher:create_question_paper' %}">Set Question Paper</a></li>
        <li><a href="{% url 'teacher:set_exam' %}">Set Exam</a></li>
        <li class="last"><a href="{% url 'main:Logout' %}" class="btn2 btn3">Logout</a></li>
      </ul>
    </div>
  </div>

templates/teacher/teacherheader.html
<header class="" id="header">
  <a href="{% url 'home' %}" class="logo" id="#logo">OPEC - Online Examination Centre</a>
  <i class="bx bx-menu" id="menu-icon"></i>
  <nav class="navbar">
    <a href="{% url 'teacher:interface' %}" class="temp">Personal Information</a>
    <!--<a href="{% url 'teacher:result' %}" class="temp">Check Results</a>-->
    <a href="{% url 'teacher:create_question' %}">Set Questions</a>
    <a href="{% url 'teacher:create_question_paper' %}">Set Question Paper</a>
    <a href="{% url 'teacher:set_exam' %}">Set Exam</a>
    <a href="{% url 'about' %}">About</a>
    <a class="btn" id="btn-color" href="{% url 'contact' %}">Contact Us</a>
  </nav>
</header>
