main/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from .views import *
urlpatterns = [
    path('register/',register_view.as_view(),name='register'),
    path('login/', UserLoginView.as_view(),name='Login' ),
    path('logout/', UserLogoutView.as_view(),{'next_page':''},name='Logout' ),
]

online_exam/urls.py
import os
from django.contrib import admin, auth
#from django.conf.urls import re_path
from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
# from ..teacher.views import QuestionList

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns = [
    path('', home,name='home'),
    path('admin/', admin.site.urls,name='admin'),
    re_path(r'^css/(?P<file>.*)$', css, name='css'),
    # path('student/', include('C:\Users\student\Desktop\Python\online_exam\teacher\urls.py')),
    path('teacher/', include((r'teacher.urls','teacher'),namespace='teacher')),
    path('student/', include((r'student.urls','student'),namespace='student')),
    re_path(r'^images/(.*)$',image , name='images'),
    path('contact/', contact,name='contact'),
    path('about/', about,name='about'),
    path('',include((r'main.urls','main'),namespace='main')),

]

student/urls.py
from django.contrib import admin, auth
from django.urls import path, include,re_path
from .views import *
urlpatterns = [
    path('', interface.as_view(),name='interface' ),
    #path('accnt/',include('django.contrib.auth.urls')),
    path('result/', Result.as_view(),name='result' ),
    path('choose_exam/', ChooseExam.as_view(),name='choose_exam' ),
    re_path(r'^exam/(?P<exam>.+)$',exam.as_view()),
]

templates/about.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>About Us - OPEC</title>

  <!--Primary meta tags -->
  <meta name="title" content="OPEC">
  <meta name="description" content="OPEC stands for online platform for Examination Center. It is a part of online examination system.">

  <!-- Stylesheet -->
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <link rel="stylesheet" href="{% static 'css/about.css' %}">

  <!-- Boxicons -->
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

</head>

<body>
  {%include 'header.html'%}
  <div class="top-div">
    <h1>About Us</h1>
  </div>
  <div class="contents">
    <p>
      At our online examination website, we are committed to providing a seamless and convenient platform for individuals and organizations to conduct and take examinations. Our goal is to provide a secure, reliable, and user-friendly platform that can be used by individuals and organizations worldwide. <br> <br>
      Our team is comprised of experts in the field of online examination, with a passion for providing the best possible experience for our users. We understand the importance of exams and the impact they can have on an individual’s education, career, and personal growth. That is why we are dedicated to providing a platform that is easy to use, yet highly secure and reliable. <br> <br>
      Our website is designed to cater to the needs of individuals and organizations who need to conduct exams online. We offer a wide range of features and tools that make the process of conducting and taking exams easier and more efficient. From customizable exam templates to advanced reporting features, we have everything you need to ensure a smooth and successful examination process. <br> <br>
      Another feature that sets us apart is our commitment to providing a user-friendly platform. We understand that not everyone is familiar with online examinations, and that is why we have designed our platform to be easy to use and navigate. From intuitive user interfaces to comprehensive tutorials, we are committed to providing a seamless and hassle-free experience for our users. <br> <br>
      At our online examination website, we pride ourselves on our ability to customize our services to meet the unique needs of our users. Whether you are an individual looking to take an online exam, or an organization looking to conduct large-scale examinations, we have the tools and expertise to meet your needs. Our team works closely with each of our clients to ensure that their needs are met, and that they are able to achieve their goals through our platform. <br> <br>
      In addition to our commitment to quality and service, we are also dedicated to innovation. We understand that technology is constantly evolving, and that is why we are always looking for new and innovative ways to improve our platform. Whether it’s through the use of artificial intelligence or other cutting-edge technologies, we are committed to staying at the forefront of online examination technology.
    </p>
  </div>

  <script src="{% static 'JS/index.js' %}"></script>
  {%include 'footer.html'%}
</body>

</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Stylesheet -->
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <link rel="stylesheet" href="{% static 'css/contact.css' %}">

  <!-- Boxicon -->
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  
  <title>Contact Us</title>
</head>
<body>
  {%include 'header.html'%}
  
  <section class="about-section">
    <h2>Contact Us</h2>
  </section>
  
  <section class="contact-section">
    <div class="getin">
      <h2>Get in touch</h2>
      <p>Looking for help? Fill the form and do let us know.</p>
  
      <div class="getin-details">
        <h3>Address</h3>
        <div>
          <i class="fa-solid fa-location-dot icon"></i>
          <p>Address</p>
        </div>
  
        <h3>Phone</h3>
        <div>
          <i class="fa-solid fa-phone icon"></i>
          <p>(+91) 1234567890</p>
        </div>
  
        <h3>Support</h3>
        <div>
          <i class="fa-solid fa-envelope icon"></i>
          <p>hr@gmail.com</p>
        </div>
      </div>
    </div>
  
    <div class="form">
      <form action="" autocomplete="off">
        <h4>Let's Connect</h4>
        <p>Do you have anything to say. Feel free to do so.</p>
        <div class="form-row">
          <input type="text" placeholder="Your Name" class="name input" id="Name" required>
          <input type="email" name="" id="Email" placeholder="Email address...." class="email input" required>
        </div>
        <div class="form-col">
          <input type="subject" placeholder="Subject" class="subject input">
        </div>
        <div class="form-col">
          <textarea name="" cols="20" rows="5" placeholder="How we can help you?" class="message" id="Message" required></textarea>
        </div>
        <div class="form-col">
          <input type="submit" value="Send message" class="send-btn" onclick="SendMail()" />
        </div>
      </form>
    </div>
  </section>
  
  {%include 'footer.html'%}

  <!-- Email.js -->
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

  <script type="text/javascript">
    (function () {
      emailjs.init("rHjGiC50R4JGT5rtA");
    })();
  </script>

  <!-- JavaScript -->
  <script src="{% static 'JS/index.js' %}"></script>

  <!-- Font Awesome Icon -->
  <script src="https://kit.fontawesome.com/2c541f9ba2.js" crossorigin="anonymous"></script>

</body>
</html>


templates/footer.html
<section class="footer">
  <div class="main">
    <div class="list list-1">
      <h2>OPEC</h2>
      <div class="comp-desc">
        <p>
          OPEC is an online platform where examinations are conducted through online medium.
        </p>
      </div>
      <br>
      <div class="comp-desc">
        <p style="font-size: 16px">For queries:</p>
        <p>opec2023@gmail.com</p>
      </div>
      <div class="social">
        <a href="#"><i class='bx bxl-facebook'></i></a>
        <a href="#"><i class='bx bxl-instagram-alt'></i></a>
        <a href="#"><i class='bx bxl-twitter'></i></a>
        <a href="#"><i class='bx bxl-youtube'></i></a>
        <a href="#"><i class='bx bxl-linkedin'></i></a>
      </div>
    </div>


    <div class="list list-2">
      <h4>Useful Links</h4>
      <ul>
        <li><a href="contact-page.html">Contact US</a></li>
        <li><a href="community.html">Our Community</a></li>
      </ul>
    </div>

    <div class="list list-3">
      <h4>Designed By</h4>
      <ul>
        <li>Md Farhan Sajid - 2060010</li>
        <li>Anshuman Dhan - 2060007</li>
        <li>Ankit Kumar - 2060029</li>
        <li>Moni Kumari - 2060009</li>
        <li>Utkarsh Didwania - 2060004</li>
      </ul>
    </div>
  </div>

  <div class="footer-end">
    <div class="end-text">
      <p>Copyright &#169;2023 All rights reserved</p>
    </div>
  </div>
</section>

templates/header.html


</head>
<body>
  <header class="" id="header">
    <a href="{% url 'home' %}" class="logo" id="#logo">OPEC - Online Examination Centre</a>
    <i class="bx bx-menu" id="menu-icon"></i>
    <nav class="navbar">
      <a href="{% url 'about' %}">About</a>
      <a class="btn" id="btn-color" href="{% url 'contact' %}">Contact Us</a>
    </nav>
  </header>

templates/index (2).html

  <section class="footer">
    <div class="main">
      <div class="list list-1">
        <h2>OPEC</h2>
        <div class="comp-desc">
          <p>
            OPEC is an online platform where examinations are conducted through online medium.
          </p>
        </div>
        <br>
        <div class="comp-desc">
          <p style="font-size: 16px">For queries:</p>
          <p>opec2023@gmail.com</p>
        </div>
        <div class="social">
          <a href="#"><i class='bx bxl-facebook'></i></a>
          <a href="#"><i class='bx bxl-instagram-alt'></i></a>
          <a href="#"><i class='bx bxl-twitter'></i></a>
          <a href="#"><i class='bx bxl-youtube'></i></a>
          <a href="#"><i class='bx bxl-linkedin'></i></a>
        </div>
      </div>


      <div class="list list-2">
        <h4>Legal</h4>
        <ul>
          <li><a href="./termsandconditions.html">Terms & Conditions</a></li>
          <li><a href="./privacy.html">Privacy Policy</a></li>
          <li><a href="./security.html">Security Policy</a></li>
          <li><a href="./codeofconduct.html">Code Of Conduct</a></li>
        </ul>
      </div>

      <div class="list list-3">
        <h4>Useful Links</h4>
        <ul>
          <li><a href="contact-page.html">Contact US</a></li>
          <li><a href="FAQ.html">FAQ</a></li>
          <li><a href="">Blogs</a></li>
        </ul>
      </div>

      <div class="list list-3">
        <h4>Designed By</h4>
        <ul>
          <li>Md Farhan Sajid - 2060010</li>
          <li>Anshuman Dhan - 2060007</li>
          <li>Ankit Kumar - 2060029</li>
          <li>Moni Kumari - 2060009</li>
          <li>Utkarsh Didwania - 2060004</li>
        </ul>
      </div>
    </div>

    <div class="footer-end">
      <div class="end-text">
        <p>Copyright &#169;2023 All rights reserved</p>
      </div>
    </div>
  </section>

templates/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OPEC - Online Platform for Examination Centre</title>
  
  <!-- Boxicon -->
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

  <!-- Custom CSS file -->
  <link rel="stylesheet" href="{% static 'css/home.css' %}" >

</head>
<body>

  {%include 'header.html'%}
  <section class="home">
    <div class="container">
      <h1>Welcome!</h1>
      <img src="{% static 'images/exam_icon.jpg' %}" alt="">
      <ul>
        <li><a href="{% url 'student:interface' %}">Student Interface</a></li>
        <li><a href="{% url 'teacher:interface' %}">Teacher Interface</a></li>
      </ul>
      <p>Don't have an account?</p>
      <a href="{% url 'main:register' %}">Register Now</a>
    </div>
  </section>

  {%include 'footer.html'%}
</body>
</html>

templates/index_form.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OPEC - Online Platform for Examination Centre</title>
  
  <!-- Boxicon -->
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

  <!-- Custom CSS file -->
  <link rel="stylesheet" href="{% static 'css/home.css' %}" >

</head>
<body>

  {%include 'header.html'%}
  <section class="home">
    <div class="container">
      <!--<form method="POST">{% csrf_token %}
        {{form.as_p}}
        <p>
          <button type="submit" class="btn btn-primary">Submit</button>
        </p>
        </form>-->
        <h1>{{message}}</h1>
    </div>
  </section>

  {%include 'footer.html'%}
</body>
</html>